name: mmdb
dependencies:
  - python=3.8
  - pip
  - pip:
    - -r requirements/requirements-db.txt
    - -r requirements/requirements-env.txt
    - -r requirements/requirements-optionals.txt
    - -r requirements/requirements-testing.txt
    - -r requirements/requirements-documentation.txt
    - -r requirements/requirements-codestyle.txt
    - -r requirements/requirements-packaging.txt