version: "3.1"

services:
  mmdb:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: mmdb
    restart: unless-stopped
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      DEBUG: ${DEBUG:-true}
      MMDB_ALLOWED_HOSTS: ${MMDB_ALLOWED_HOSTS:-*}
      MMDB_DEBUG: ${MMDB_DEBUG:-true}
      MMDB_PORT: ${MMDB_PORT:-8002}
      MMDB_SECRET_KEY: ${MMDB_SECRET_KEY}
      SQL_DATABASE: ${SQL_DATABASE:-mmdb}
      SQL_HOST: ${SQL_HOST:-localhost}
      SQL_PORT: ${SQL_PORT:-3306}
      SQL_USER: ${SQL_USER:-mmdb}
      SQL_PASSWORD: ${SQL_PASSWORD}
      GUNICORN_OPTS: ${GUNICORN_OPTS:-}
      MMDB_GUNICORN_OPTS: ${GUNICORN_OPTS:-}