version: "3.1"

volumes:
  mmdbstatic:

services:
  mmdb:
    image: mmdb
    restart: unless-stopped
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG:-false}
      MMDB_ALLOWED_HOSTS: ${MMDB_ALLOWED_HOSTS}
      MMDB_DEBUG: ${MMDB_DEBUG:-false}
      MMDB_PORT: ${MMDB_PORT:-8002}
      MMDB_SECRET_KEY: ${MMDB_SECRET_KEY}
      SQL_DATABASE: ${SQL_DATABASE:-mmdb}
      SQL_HOST: ${SQL_HOST:-localhost}
      SQL_PORT: ${SQL_PORT:-3306}
      SQL_USER: ${SQL_USER:-mmdb}
      SQL_PASSWORD: ${SQL_PASSWORD:-mmdb}
      GUNICORN_OPTS: ${GUNICORN_OPTS:-}
      MMDB_GUNICORN_OPTS: ${GUNICORN_OPTS:-}
    volumes:
      - mmdbstatic:/app/collected_static

  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - ${MMDB_PORT:-8002}:${MMDB_PORT:-8002}
    volumes:
      - mmdbstatic:/app/collected_static:ro
    depends_on:
      - mmdb
    entrypoint: >
      sh -c "
        rm /etc/nginx/conf.d/default.conf \
        && echo \"
          upstream mmdb {
              server mmdb:${MMDB_PORT:-8002};
          }
          server {
              listen ${MMDB_PORT:-8002} default_server;
              server_name _;
              charset utf-8;
              client_max_body_size 0;
              location /static {
                  alias /app/collected_static;
              }
              location /favicon.ico {
                  access_log off;
                  log_not_found off;
              }
              location / {
                  proxy_set_header Host \$$http_host;
                  proxy_pass http://mmdb;
                  access_log off;
              }
          }
        \" > /etc/nginx/conf.d/default.conf \
        && exec nginx -g 'daemon off;'
      "

