# Generated by Django 3.1.4 on 2020-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('who', models.CharField(max_length=100)),
                ('sourcetype', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('oppt_phase', models.IntegerField()),
                ('processed', models.IntegerField()),
                ('harm_init', models.IntegerField()),
                ('harm_mapped', models.IntegerField()),
                ('loaded', models.IntegerField()),
                ('icfsource', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
